authors: []
blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -DPYTHON_EXECUTABLE=/home/ltoschi/.pyenv/versions/ros_inference_ic/bin/python3
- -DPYTHON_INCLUDE_DIR=/home/ltoschi/.pyenv/versions/3.7.6/include/python3.7m
- -DPYTHON_LIBRARY=/home/ltoschi/.pyenv/versions/3.7.6/lib
devel_layout: linked
devel_space: devel
extend_path: null
extends: null
install: true
install_space: install
isolate_install: false
jobs_args: []
licenses:
- TODO
log_space: logs
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
